# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yagura < Formula
  desc "Agent-first multi-repo git worktree cockpit for the terminal"
  homepage "https://github.com/zeroblack/yagura"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeroblack/yagura/releases/download/v0.4.1/yagura_0.4.1_darwin_amd64.tar.gz"
      sha256 "6937aeb939402836b3b3f0f0dd2bb70acc4a6f9b546d54b6e6625b2ea0635d38"

      define_method(:install) do
        bin.install "yagura"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeroblack/yagura/releases/download/v0.4.1/yagura_0.4.1_darwin_arm64.tar.gz"
      sha256 "2d406eb9d618f4c596e3cd9af6816c92df848a65e5979e26162b371a1e6f88b0"

      define_method(:install) do
        bin.install "yagura"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeroblack/yagura/releases/download/v0.4.1/yagura_0.4.1_linux_amd64.tar.gz"
      sha256 "dce7ca45e9969251ebc3d3dc9937776d913ca0f03b0d46632fddf112cef848fa"
      define_method(:install) do
        bin.install "yagura"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeroblack/yagura/releases/download/v0.4.1/yagura_0.4.1_linux_arm64.tar.gz"
      sha256 "027a2a1dcc1726d09df532de4a5dccaf6f154cbcda0145c53019426f34e7ec34"
      define_method(:install) do
        bin.install "yagura"
      end
    end
  end

  test do
    system "#{bin}/yagura", "doctor"
  end
end
