# This file was generated by GoReleaser. DO NOT EDIT.
cask "yagura" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "53cb09bd4a1a34875b24344cb5ea56876752a775819cd2af92b89d4223fe8875"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b47481901c11949da8e0bec16300e88b32b791eca2558c16a0e14fbe016044fd"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1359bc83eb69d2c0891d362c3e1934d7d2b3efd2d825d644a018a865ec36b62"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7117cefd9df3d05c3ba6723b78e0d43773a0daca7661ae08c88b75fb94de9053"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yagura"
  desc "Agent-first multi-repo git worktree cockpit for the terminal"
  homepage "https://github.com/zeroblack/yagura"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yagura"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yagura"]
    end
  end

  # No zap stanza required

end
