# This file was generated by GoReleaser. DO NOT EDIT.
cask "yagura" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "1b2f7d97711a8c3aec6e12ae0ea47e6cbabd8d747a1ae50af212acc26ab1d2d7"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f00ad504143640748e45e5f5dc859673c6352707254470cdbe68c704436b107a"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "15f3a4724cf1cd781e82da81ac0316838e6e5ab00011a746ec2479f725a31e39"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "efda037818ae4921d8b22efc6efe314bda63c0333602a2d266a8e35ff3f249d2"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yagura"
  desc "Agent-first multi-repo git worktree cockpit for the terminal"
  homepage "https://github.com/zeroblack/yagura"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yagura"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yagura"]
    end
  end

  # No zap stanza required

end
