# This file was generated by GoReleaser. DO NOT EDIT.
cask "yagura" do
  version "0.4.5"

  on_macos do
    on_intel do
      sha256 "b1576d7fb733f6cc2cc0e051a4c3bd9259c278f5e100be355b594c56322e1e98"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "383a22c78c723ca0eecc27d27258cb3ce668cfb47da05560f1aee57fdeeb8bf5"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b98b8efb816cb998c04efc2686118a81c5e4c47e9dda7ae8170a73c4d028903"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "46a7915c2415f079ea367be680b23729c62cd2f47c1c0729a41ebd6c7c75f79c"
      url "https://github.com/zeroblack/yagura/releases/download/v#{version}/yagura_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yagura"
  desc "Agent-first multi-repo git worktree cockpit for the terminal"
  homepage "https://github.com/zeroblack/yagura"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yagura"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yagura"]
    end
  end

  # No zap stanza required

end
